# Generated by Django 4.2.7 on 2023-11-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_bookreview_loan_remove_magazine_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['author', 'title']},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['book', 'borrow_date']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='Availability',
        ),
        migrations.AddField(
            model_name='book',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Availability'),
        ),
    ]
